jobs:

################################################################################
- job: build_linux_arm_agent
################################################################################
  displayName: Linux Agent (ARM)
  pool:
    name: default
    demands: 'Agent.OSArchitecture -equals ARM'
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
